<?php

namespace Database\Seeders;

use App\Models\Customer;
use App\Models\User;
use Illuminate\Database\Seeder;

class CustomerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $adminUser = User::first();
        $createdBy = $adminUser ? $adminUser->id : null;

        $customers = [
            // VIP Customers
            [
                'code' => 'CUST001',
                'name' => 'PT Maju Jaya Sentosa',
                'company_name' => 'PT Maju Jaya Sentosa',
                'email' => 'purchasing@majujaya.co.id',
                'phone' => '021-5551234',
                'address' => 'Jl. Sudirman Kav. 52-53, SCBD',
                'city' => 'Jakarta Selatan',
                'province' => 'DKI Jakarta',
                'postal_code' => '12190',
                'country' => 'Indonesia',
                'tax_id' => '01.234.567.8-901.000',
                'customer_type' => 'vip',
                'credit_limit' => 5000000000.00,
                'payment_terms_days' => 60,
                'contact_person' => 'Budi Santoso',
                'contact_phone' => '0812-3456-7890',
                'is_active' => true,
                'notes' => 'Customer VIP dengan volume order tinggi',
                'created_by' => $createdBy,
            ],
            [
                'code' => 'CUST002',
                'name' => 'PT Berkah Elektronik Indonesia',
                'company_name' => 'PT Berkah Elektronik Indonesia',
                'email' => 'procurement@berkahelektronik.com',
                'phone' => '021-5557890',
                'address' => 'Jl. Gatot Subroto Kav. 21',
                'city' => 'Jakarta Pusat',
                'province' => 'DKI Jakarta',
                'postal_code' => '10270',
                'country' => 'Indonesia',
                'tax_id' => '02.345.678.9-012.000',
                'customer_type' => 'vip',
                'credit_limit' => 3000000000.00,
                'payment_terms_days' => 45,
                'contact_person' => 'Siti Nurhaliza',
                'contact_phone' => '0813-4567-8901',
                'is_active' => true,
                'notes' => 'Distributor elektronik terbesar',
                'created_by' => $createdBy,
            ],

            // Wholesale Customers
            [
                'code' => 'CUST003',
                'name' => 'CV Cahaya Abadi',
                'company_name' => 'CV Cahaya Abadi',
                'email' => 'order@cahayaabadi.co.id',
                'phone' => '031-7654321',
                'address' => 'Jl. Raya Darmo No. 123',
                'city' => 'Surabaya',
                'province' => 'Jawa Timur',
                'postal_code' => '60264',
                'country' => 'Indonesia',
                'tax_id' => '03.456.789.0-123.000',
                'customer_type' => 'wholesale',
                'credit_limit' => 1500000000.00,
                'payment_terms_days' => 30,
                'contact_person' => 'Ahmad Yani',
                'contact_phone' => '0851-2345-6789',
                'is_active' => true,
                'notes' => 'Grosir dengan jaringan retail luas',
                'created_by' => $createdBy,
            ],
            [
                'code' => 'CUST004',
                'name' => 'PT Sumber Rejeki Makmur',
                'company_name' => 'PT Sumber Rejeki Makmur',
                'email' => 'admin@sumberrejeki.com',
                'phone' => '022-8765432',
                'address' => 'Jl. Asia Afrika No. 88',
                'city' => 'Bandung',
                'province' => 'Jawa Barat',
                'postal_code' => '40111',
                'country' => 'Indonesia',
                'tax_id' => '04.567.890.1-234.000',
                'customer_type' => 'wholesale',
                'credit_limit' => 2000000000.00,
                'payment_terms_days' => 30,
                'contact_person' => 'Dewi Lestari',
                'contact_phone' => '0822-3456-7890',
                'is_active' => true,
                'notes' => 'Wholesaler dengan fokus FMCG',
                'created_by' => $createdBy,
            ],
            [
                'code' => 'CUST005',
                'name' => 'UD Karya Mandiri',
                'company_name' => 'UD Karya Mandiri',
                'email' => 'contact@karyamandiri.net',
                'phone' => '061-4567890',
                'address' => 'Jl. Sisingamangaraja No. 45',
                'city' => 'Medan',
                'province' => 'Sumatera Utara',
                'postal_code' => '20217',
                'country' => 'Indonesia',
                'tax_id' => '05.678.901.2-345.000',
                'customer_type' => 'wholesale',
                'credit_limit' => 1000000000.00,
                'payment_terms_days' => 30,
                'contact_person' => 'Rina Sari',
                'contact_phone' => '0813-5678-9012',
                'is_active' => true,
                'notes' => 'Distributor regional Sumatera',
                'created_by' => $createdBy,
            ],

            // Regular Customers
            [
                'code' => 'CUST006',
                'name' => 'Toko Sejahtera',
                'company_name' => 'Toko Sejahtera',
                'email' => 'tokosejahtera@gmail.com',
                'phone' => '024-7654321',
                'address' => 'Jl. Pemuda No. 156',
                'city' => 'Semarang',
                'province' => 'Jawa Tengah',
                'postal_code' => '50132',
                'country' => 'Indonesia',
                'tax_id' => '06.789.012.3-456.000',
                'customer_type' => 'regular',
                'credit_limit' => 500000000.00,
                'payment_terms_days' => 30,
                'contact_person' => 'Hendra Wijaya',
                'contact_phone' => '0856-7890-1234',
                'is_active' => true,
                'notes' => 'Toko retail menengah',
                'created_by' => $createdBy,
            ],
            [
                'code' => 'CUST007',
                'name' => 'CV Tiga Saudara',
                'company_name' => 'CV Tiga Saudara',
                'email' => 'tigasaudara@yahoo.com',
                'phone' => '0274-567890',
                'address' => 'Jl. Malioboro No. 99',
                'city' => 'Yogyakarta',
                'province' => 'DI Yogyakarta',
                'postal_code' => '55271',
                'country' => 'Indonesia',
                'tax_id' => '07.890.123.4-567.000',
                'customer_type' => 'regular',
                'credit_limit' => 300000000.00,
                'payment_terms_days' => 30,
                'contact_person' => 'Agus Prasetyo',
                'contact_phone' => '0878-9012-3456',
                'is_active' => true,
                'notes' => 'Toko souvenir dan retail',
                'created_by' => $createdBy,
            ],
            [
                'code' => 'CUST008',
                'name' => 'Minimarket Bahagia',
                'company_name' => 'Minimarket Bahagia',
                'email' => 'minimarket.bahagia@gmail.com',
                'phone' => '0361-234567',
                'address' => 'Jl. Sunset Road No. 77',
                'city' => 'Denpasar',
                'province' => 'Bali',
                'postal_code' => '80361',
                'country' => 'Indonesia',
                'tax_id' => '08.901.234.5-678.000',
                'customer_type' => 'regular',
                'credit_limit' => 250000000.00,
                'payment_terms_days' => 14,
                'contact_person' => 'Made Suarjana',
                'contact_phone' => '0812-4567-8901',
                'is_active' => true,
                'notes' => 'Minimarket lokal',
                'created_by' => $createdBy,
            ],
            [
                'code' => 'CUST009',
                'name' => 'Toko Serba Ada',
                'company_name' => 'Toko Serba Ada',
                'email' => 'serba.ada@outlook.com',
                'phone' => '0511-345678',
                'address' => 'Jl. Ahmad Yani KM 5',
                'city' => 'Banjarmasin',
                'province' => 'Kalimantan Selatan',
                'postal_code' => '70123',
                'country' => 'Indonesia',
                'tax_id' => '09.012.345.6-789.000',
                'customer_type' => 'regular',
                'credit_limit' => 200000000.00,
                'payment_terms_days' => 30,
                'contact_person' => 'Bambang Sutrisno',
                'contact_phone' => '0852-6789-0123',
                'is_active' => true,
                'notes' => 'Toko kelontong besar',
                'created_by' => $createdBy,
            ],
            [
                'code' => 'CUST010',
                'name' => 'UD Makmur Jaya',
                'company_name' => 'UD Makmur Jaya',
                'email' => 'makmurjaya@gmail.com',
                'phone' => '0411-456789',
                'address' => 'Jl. Pettarani No. 45',
                'city' => 'Makassar',
                'province' => 'Sulawesi Selatan',
                'postal_code' => '90222',
                'country' => 'Indonesia',
                'tax_id' => '10.123.456.7-890.000',
                'customer_type' => 'regular',
                'credit_limit' => 400000000.00,
                'payment_terms_days' => 30,
                'contact_person' => 'Andi Mappanyukki',
                'contact_phone' => '0813-7890-1234',
                'is_active' => true,
                'notes' => 'Distributor regional Sulawesi',
                'created_by' => $createdBy,
            ],
            [
                'code' => 'CUST011',
                'name' => 'CV Harapan Baru',
                'company_name' => 'CV Harapan Baru',
                'email' => 'harapanbaru@mail.com',
                'phone' => '0542-567890',
                'address' => 'Jl. Sudirman No. 123',
                'city' => 'Balikpapan',
                'province' => 'Kalimantan Timur',
                'postal_code' => '76114',
                'country' => 'Indonesia',
                'tax_id' => '11.234.567.8-901.000',
                'customer_type' => 'regular',
                'credit_limit' => 350000000.00,
                'payment_terms_days' => 30,
                'contact_person' => 'Joko Widodo',
                'contact_phone' => '0821-8901-2345',
                'is_active' => true,
                'notes' => 'Toko retail dan grosir',
                'created_by' => $createdBy,
            ],
            [
                'code' => 'CUST012',
                'name' => 'Toko Elektronik Jaya',
                'company_name' => 'Toko Elektronik Jaya',
                'email' => 'elektronikjaya@gmail.com',
                'phone' => '0751-234567',
                'address' => 'Jl. Sudirman No. 88',
                'city' => 'Padang',
                'province' => 'Sumatera Barat',
                'postal_code' => '25117',
                'country' => 'Indonesia',
                'tax_id' => '12.345.678.9-012.000',
                'customer_type' => 'regular',
                'credit_limit' => 450000000.00,
                'payment_terms_days' => 30,
                'contact_person' => 'Rahman Hakim',
                'contact_phone' => '0822-9012-3456',
                'is_active' => true,
                'notes' => 'Spesialis elektronik',
                'created_by' => $createdBy,
            ],
            [
                'code' => 'CUST013',
                'name' => 'PT Nusantara Raya',
                'company_name' => 'PT Nusantara Raya',
                'email' => 'info@nusantararaya.co.id',
                'phone' => '0721-345678',
                'address' => 'Jl. Raden Intan No. 56',
                'city' => 'Bandar Lampung',
                'province' => 'Lampung',
                'postal_code' => '35214',
                'country' => 'Indonesia',
                'tax_id' => '13.456.789.0-123.000',
                'customer_type' => 'regular',
                'credit_limit' => 600000000.00,
                'payment_terms_days' => 30,
                'contact_person' => 'Sri Mulyani',
                'contact_phone' => '0813-0123-4567',
                'is_active' => true,
                'notes' => 'Distributor multi kategori',
                'created_by' => $createdBy,
            ],
            [
                'code' => 'CUST014',
                'name' => 'UD Mitra Usaha',
                'company_name' => 'UD Mitra Usaha',
                'email' => 'mitrausaha@yahoo.co.id',
                'phone' => '0341-456789',
                'address' => 'Jl. Ijen No. 77',
                'city' => 'Malang',
                'province' => 'Jawa Timur',
                'postal_code' => '65119',
                'country' => 'Indonesia',
                'tax_id' => '14.567.890.1-234.000',
                'customer_type' => 'regular',
                'credit_limit' => 280000000.00,
                'payment_terms_days' => 30,
                'contact_person' => 'Dian Pertiwi',
                'contact_phone' => '0856-1234-5678',
                'is_active' => true,
                'notes' => 'Fokus produk FMCG',
                'created_by' => $createdBy,
            ],
            [
                'code' => 'CUST015',
                'name' => 'Toko Global Mart',
                'company_name' => 'Toko Global Mart',
                'email' => 'globalmart@gmail.com',
                'phone' => '0778-567890',
                'address' => 'Jl. Hang Tuah No. 99',
                'city' => 'Tanjung Pinang',
                'province' => 'Kepulauan Riau',
                'postal_code' => '29111',
                'country' => 'Indonesia',
                'tax_id' => '15.678.901.2-345.000',
                'customer_type' => 'regular',
                'credit_limit' => 320000000.00,
                'payment_terms_days' => 30,
                'contact_person' => 'Linda Wijaya',
                'contact_phone' => '0877-2345-6789',
                'is_active' => true,
                'notes' => 'Supermarket lokal',
                'created_by' => $createdBy,
            ],

            // Inactive Customer (contoh)
            [
                'code' => 'CUST016',
                'name' => 'CV Matahari Terbenam',
                'company_name' => 'CV Matahari Terbenam',
                'email' => 'matahariterbenam@mail.com',
                'phone' => '021-9876543',
                'address' => 'Jl. Veteran No. 123',
                'city' => 'Jakarta Barat',
                'province' => 'DKI Jakarta',
                'postal_code' => '11420',
                'country' => 'Indonesia',
                'tax_id' => '16.789.012.3-456.000',
                'customer_type' => 'regular',
                'credit_limit' => 150000000.00,
                'payment_terms_days' => 30,
                'contact_person' => 'Thomas Anderson',
                'contact_phone' => '0812-9876-5432',
                'is_active' => false,
                'notes' => 'Customer tidak aktif - tunggakan pembayaran',
                'created_by' => $createdBy,
            ],
        ];

        foreach ($customers as $customer) {
            Customer::create($customer);
        }

        $this->command->info('Created ' . count($customers) . ' customers successfully!');
    }
}