<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\ProductCategory;
use App\Models\Unit;
use App\Models\Supplier;
use App\Models\User;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $adminUser = User::first();
        $createdBy = $adminUser ? $adminUser->id : null;

        // Ambil categories, units, dan suppliers
        $categories = ProductCategory::all();
        $units = Unit::all();
        $suppliers = Supplier::all();

        if ($categories->isEmpty()) {
            $this->command->warn('Tidak ada product category. Jalankan ProductCategorySeeder terlebih dahulu.');
            return;
        }

        if ($units->isEmpty()) {
            $this->command->warn('Tidak ada units. Jalankan UnitSeeder terlebih dahulu.');
            return;
        }

        $products = [
            // ========================================
            // ELECTRONICS - Smartphones
            // ========================================
            [
                'sku' => 'ELC-SM-001',
                'barcode' => '8991234567001',
                'name' => 'Samsung Galaxy S24 Ultra 512GB',
                'description' => 'Smartphone flagship dengan kamera 200MP, layar AMOLED 6.8 inch, prosesor Snapdragon 8 Gen 3, RAM 12GB, storage 512GB, S-Pen included, IP68 water resistant',
                'category_id' => $this->getCategoryId($categories, 'Smartphones'),
                'brand' => 'Samsung',
                'unit_id' => $this->getUnitId($units, 'Piece'),
                'supplier_id' => $this->getSupplierId($suppliers, 'Electronics Supplier'),
                'purchase_price' => 16500000.00,
                'selling_price' => 19999000.00,
                'minimum_selling_price' => 18500000.00,
                'minimum_stock' => 20,
                'maximum_stock' => 300,
                'reorder_level' => 40,
                'current_stock' => 85,
                'weight' => 0.23,
                'length' => 16.28,
                'width' => 7.91,
                'height' => 0.88,
                'is_taxable' => true,
                'tax_rate' => 11.00,
                'type' => 'finished_goods',
                'is_active' => true,
                'is_serialized' => true,
                'is_batch_tracked' => true,
                'notes' => 'High-end smartphone dengan garansi resmi SEIN 1 tahun. Serial number tracking mandatory.',
                'created_by' => $createdBy,
            ],
            [
                'sku' => 'ELC-SM-002',
                'barcode' => '8991234567002',
                'name' => 'iPhone 15 Pro Max 256GB',
                'description' => 'iPhone terbaru dengan chip A17 Pro, kamera 48MP ProRAW, layar Super Retina XDR 6.7 inch, titanium design, Action Button, USB-C port',
                'category_id' => $this->getCategoryId($categories, 'Smartphones'),
                'brand' => 'Apple',
                'unit_id' => $this->getUnitId($units, 'Piece'),
                'supplier_id' => $this->getSupplierId($suppliers, 'Electronics Supplier'),
                'purchase_price' => 19500000.00,
                'selling_price' => 23999000.00,
                'minimum_selling_price' => 22000000.00,
                'minimum_stock' => 15,
                'maximum_stock' => 250,
                'reorder_level' => 30,
                'current_stock' => 65,
                'weight' => 0.22,
                'length' => 15.99,
                'width' => 7.68,
                'height' => 0.83,
                'is_taxable' => true,
                'tax_rate' => 11.00,
                'type' => 'finished_goods',
                'is_active' => true,
                'is_serialized' => true,
                'is_batch_tracked' => true,
                'notes' => 'Premium smartphone dengan garansi resmi iBox/Digimap 1 tahun. IMEI tracking required.',
                'created_by' => $createdBy,
            ],

            // ========================================
            // ELECTRONICS - Laptops
            // ========================================
            [
                'sku' => 'ELC-LT-001',
                'barcode' => '8991234567003',
                'name' => 'MacBook Pro 16" M3 Max 64GB 2TB',
                'description' => 'Laptop profesional dengan chip M3 Max, RAM 64GB unified memory, SSD 2TB, layar Liquid Retina XDR 16.2 inch, 6 Thunderbolt 4 ports, battery 100Wh',
                'category_id' => $this->getCategoryId($categories, 'Computers'),
                'brand' => 'Apple',
                'unit_id' => $this->getUnitId($units, 'Piece'),
                'supplier_id' => $this->getSupplierId($suppliers, 'Electronics Supplier'),
                'purchase_price' => 75000000.00,
                'selling_price' => 89999000.00,
                'minimum_selling_price' => 82000000.00,
                'minimum_stock' => 5,
                'maximum_stock' => 100,
                'reorder_level' => 10,
                'current_stock' => 22,
                'weight' => 2.15,
                'length' => 35.57,
                'width' => 24.81,
                'height' => 1.68,
                'is_taxable' => true,
                'tax_rate' => 11.00,
                'type' => 'finished_goods',
                'is_active' => true,
                'is_serialized' => true,
                'is_batch_tracked' => true,
                'notes' => 'Professional laptop untuk creative professionals. Garansi resmi 1 tahun.',
                'created_by' => $createdBy,
            ],
            [
                'sku' => 'ELC-LT-002',
                'barcode' => '8991234567004',
                'name' => 'Dell XPS 15 i9 32GB 1TB RTX4060',
                'description' => 'Laptop high-performance dengan Intel Core i9-13900H, RAM 32GB DDR5, SSD 1TB NVMe, NVIDIA RTX 4060 8GB, layar OLED 15.6 inch 4K touch',
                'category_id' => $this->getCategoryId($categories, 'Computers'),
                'brand' => 'Dell',
                'unit_id' => $this->getUnitId($units, 'Piece'),
                'supplier_id' => $this->getSupplierId($suppliers, 'Electronics Supplier'),
                'purchase_price' => 38000000.00,
                'selling_price' => 45999000.00,
                'minimum_selling_price' => 42000000.00,
                'minimum_stock' => 8,
                'maximum_stock' => 120,
                'reorder_level' => 15,
                'current_stock' => 35,
                'weight' => 1.96,
                'length' => 34.45,
                'width' => 23.04,
                'height' => 1.80,
                'is_taxable' => true,
                'tax_rate' => 11.00,
                'type' => 'finished_goods',
                'is_active' => true,
                'is_serialized' => true,
                'is_batch_tracked' => true,
                'notes' => 'Gaming dan content creation laptop. Garansi resmi Dell Indonesia 2 tahun.',
                'created_by' => $createdBy,
            ],

            // ========================================
            // FOOD & BEVERAGE - Instant Noodles
            // ========================================
            [
                'sku' => 'FNB-IN-001',
                'barcode' => '8992234567001',
                'name' => 'Indomie Goreng 85g (Karton isi 40 pcs)',
                'description' => 'Mi instan goreng original rasa klasik favorit Indonesia, bumbu lengkap 5 sachet (bumbu, kecap manis, minyak bumbu, cabe, bawang goreng)',
                'category_id' => $this->getCategoryId($categories, 'Consumables'),
                'brand' => 'Indomie',
                'unit_id' => $this->getUnitId($units, 'Carton'),
                'supplier_id' => $this->getSupplierId($suppliers, 'Food Supplier'),
                'purchase_price' => 98000.00,
                'selling_price' => 128000.00,
                'minimum_selling_price' => 115000.00,
                'minimum_stock' => 200,
                'maximum_stock' => 5000,
                'reorder_level' => 400,
                'current_stock' => 1250,
                'weight' => 3.60,
                'length' => 42.00,
                'width' => 28.00,
                'height' => 18.00,
                'is_taxable' => true,
                'tax_rate' => 11.00,
                'type' => 'consumable',
                'is_active' => true,
                'is_serialized' => false,
                'is_batch_tracked' => true,
                'notes' => 'Expiry date tracking mandatory. Shelf life 12 bulan. Store in cool dry place.',
                'created_by' => $createdBy,
            ],
            [
                'sku' => 'FNB-IN-002',
                'barcode' => '8992234567002',
                'name' => 'Indomie Soto 75g (Karton isi 40 pcs)',
                'description' => 'Mi instan kuah rasa soto ayam khas Indonesia dengan bumbu rempah tradisional',
                'category_id' => $this->getCategoryId($categories, 'Consumables'),
                'brand' => 'Indomie',
                'unit_id' => $this->getUnitId($units, 'Carton'),
                'supplier_id' => $this->getSupplierId($suppliers, 'Food Supplier'),
                'purchase_price' => 95000.00,
                'selling_price' => 125000.00,
                'minimum_selling_price' => 112000.00,
                'minimum_stock' => 200,
                'maximum_stock' => 5000,
                'reorder_level' => 400,
                'current_stock' => 980,
                'weight' => 3.20,
                'length' => 42.00,
                'width' => 28.00,
                'height' => 18.00,
                'is_taxable' => true,
                'tax_rate' => 11.00,
                'type' => 'consumable',
                'is_active' => true,
                'is_serialized' => false,
                'is_batch_tracked' => true,
                'notes' => 'Batch tracking untuk expiry control. Shelf life 12 bulan.',
                'created_by' => $createdBy,
            ],

            // ========================================
            // BEVERAGES
            // ========================================
            [
                'sku' => 'FNB-BV-001',
                'barcode' => '8992234567010',
                'name' => 'Coca Cola 330ml Can (Karton isi 24 pcs)',
                'description' => 'Minuman berkarbonasi kemasan kaleng aluminium, original taste, no sugar, refreshing cola flavor',
                'category_id' => $this->getCategoryId($categories, 'Consumables'),
                'brand' => 'Coca Cola',
                'unit_id' => $this->getUnitId($units, 'Carton'),
                'supplier_id' => $this->getSupplierId($suppliers, 'Food Supplier'),
                'purchase_price' => 98000.00,
                'selling_price' => 135000.00,
                'minimum_selling_price' => 120000.00,
                'minimum_stock' => 300,
                'maximum_stock' => 10000,
                'reorder_level' => 600,
                'current_stock' => 2850,
                'weight' => 8.64,
                'length' => 33.00,
                'width' => 22.00,
                'height' => 13.00,
                'is_taxable' => true,
                'tax_rate' => 11.00,
                'type' => 'consumable',
                'is_active' => true,
                'is_serialized' => false,
                'is_batch_tracked' => true,
                'notes' => 'Refrigerated storage recommended 4-8°C. Batch tracking untuk best before date.',
                'created_by' => $createdBy,
            ],
            [
                'sku' => 'FNB-BV-002',
                'barcode' => '8992234567011',
                'name' => 'Aqua Botol 600ml (Karton isi 24 pcs)',
                'description' => 'Air mineral dalam kemasan botol PET 600ml, sumber mata air pegunungan, mineral alami',
                'category_id' => $this->getCategoryId($categories, 'Consumables'),
                'brand' => 'Aqua',
                'unit_id' => $this->getUnitId($units, 'Carton'),
                'supplier_id' => $this->getSupplierId($suppliers, 'Food Supplier'),
                'purchase_price' => 35000.00,
                'selling_price' => 48000.00,
                'minimum_selling_price' => 42000.00,
                'minimum_stock' => 500,
                'maximum_stock' => 20000,
                'reorder_level' => 1000,
                'current_stock' => 5600,
                'weight' => 15.00,
                'length' => 40.00,
                'width' => 27.00,
                'height' => 21.00,
                'is_taxable' => true,
                'tax_rate' => 11.00,
                'type' => 'consumable',
                'is_active' => true,
                'is_serialized' => false,
                'is_batch_tracked' => true,
                'notes' => 'Store away from direct sunlight. Shelf life 24 bulan.',
                'created_by' => $createdBy,
            ],

            // ========================================
            // RAW MATERIALS - Metals
            // ========================================
            [
                'sku' => 'RAW-MT-001',
                'barcode' => '8993234567001',
                'name' => 'Steel Plate SPCC 1.0mm (4x8 feet)',
                'description' => 'Cold rolled steel plate SPCC thickness 1.0mm, dimension 4x8 feet (1220x2440mm), surface finish mill finish, untuk stamping dan bending',
                'category_id' => $this->getCategoryId($categories, 'Metals'),
                'brand' => 'BlueScope',
                'unit_id' => $this->getUnitId($units, 'Sheet'),
                'supplier_id' => $this->getSupplierId($suppliers, 'Material Supplier'),
                'purchase_price' => 285000.00,
                'selling_price' => 365000.00,
                'minimum_selling_price' => 320000.00,
                'minimum_stock' => 30,
                'maximum_stock' => 400,
                'reorder_level' => 60,
                'current_stock' => 125,
                'weight' => 23.50,
                'length' => 244.00,
                'width' => 122.00,
                'height' => 0.10,
                'is_taxable' => true,
                'tax_rate' => 11.00,
                'type' => 'raw_material',
                'is_active' => true,
                'is_serialized' => false,
                'is_batch_tracked' => true,
                'notes' => 'For manufacturing purposes. Mill certificate required per batch. Store in dry covered area.',
                'created_by' => $createdBy,
            ],
            [
                'sku' => 'RAW-MT-002',
                'barcode' => '8993234567002',
                'name' => 'Stainless Steel SUS304 2.0mm (4x8 feet)',
                'description' => 'Stainless steel plate SUS304 (18Cr-8Ni) thickness 2.0mm, dimension 4x8 feet, 2B finish, corrosion resistant',
                'category_id' => $this->getCategoryId($categories, 'Metals'),
                'brand' => 'POSCO',
                'unit_id' => $this->getUnitId($units, 'Sheet'),
                'supplier_id' => $this->getSupplierId($suppliers, 'Material Supplier'),
                'purchase_price' => 1850000.00,
                'selling_price' => 2350000.00,
                'minimum_selling_price' => 2100000.00,
                'minimum_stock' => 20,
                'maximum_stock' => 200,
                'reorder_level' => 35,
                'current_stock' => 68,
                'weight' => 47.00,
                'length' => 244.00,
                'width' => 122.00,
                'height' => 0.20,
                'is_taxable' => true,
                'tax_rate' => 11.00,
                'type' => 'raw_material',
                'is_active' => true,
                'is_serialized' => false,
                'is_batch_tracked' => true,
                'notes' => 'Premium grade stainless. Material certificate per batch. Careful handling to avoid scratches.',
                'created_by' => $createdBy,
            ],

            // ========================================
            // RAW MATERIALS - Plastics
            // ========================================
            [
                'sku' => 'RAW-PL-001',
                'barcode' => '8993234567010',
                'name' => 'HDPE Plastic Pellets Natural (25kg/bag)',
                'description' => 'High-density polyethylene (HDPE) virgin pellets natural color, injection molding grade, MFI 8-12, untuk produksi plastic parts',
                'category_id' => $this->getCategoryId($categories, 'Plastics'),
                'brand' => 'Dow Chemical',
                'unit_id' => $this->getUnitId($units, 'Bag'),
                'supplier_id' => $this->getSupplierId($suppliers, 'Material Supplier'),
                'purchase_price' => 625000.00,
                'selling_price' => 785000.00,
                'minimum_selling_price' => 720000.00,
                'minimum_stock' => 100,
                'maximum_stock' => 2000,
                'reorder_level' => 200,
                'current_stock' => 485,
                'weight' => 25.00,
                'length' => 60.00,
                'width' => 40.00,
                'height' => 15.00,
                'is_taxable' => true,
                'tax_rate' => 11.00,
                'type' => 'raw_material',
                'is_active' => true,
                'is_serialized' => false,
                'is_batch_tracked' => true,
                'notes' => 'Store in dry place, away from heat source. COA (Certificate of Analysis) per batch.',
                'created_by' => $createdBy,
            ],
            [
                'sku' => 'RAW-PL-002',
                'barcode' => '8993234567011',
                'name' => 'PP Plastic Pellets Black (25kg/bag)',
                'description' => 'Polypropylene (PP) pellets black masterbatch, injection molding grade, MFI 15-20, UV stabilized',
                'category_id' => $this->getCategoryId($categories, 'Plastics'),
                'brand' => 'LG Chem',
                'unit_id' => $this->getUnitId($units, 'Bag'),
                'supplier_id' => $this->getSupplierId($suppliers, 'Material Supplier'),
                'purchase_price' => 485000.00,
                'selling_price' => 625000.00,
                'minimum_selling_price' => 575000.00,
                'minimum_stock' => 100,
                'maximum_stock' => 2000,
                'reorder_level' => 200,
                'current_stock' => 320,
                'weight' => 25.00,
                'length' => 60.00,
                'width' => 40.00,
                'height' => 15.00,
                'is_taxable' => true,
                'tax_rate' => 11.00,
                'type' => 'raw_material',
                'is_active' => true,
                'is_serialized' => false,
                'is_batch_tracked' => true,
                'notes' => 'Batch tracking untuk quality control. Store in dry covered area max 30°C.',
                'created_by' => $createdBy,
            ],

            // ========================================
            // SPARE PARTS - Bearings
            // ========================================
            [
                'sku' => 'SPR-BR-001',
                'barcode' => '8994234567001',
                'name' => 'Deep Groove Ball Bearing 6205 ZZ (25x52x15mm)',
                'description' => 'Deep groove ball bearing 6205 ZZ dengan shield kedua sisi, inner diameter 25mm, outer diameter 52mm, width 15mm, untuk motor industri',
                'category_id' => $this->getCategoryId($categories, 'Spare Parts'),
                'brand' => 'SKF',
                'unit_id' => $this->getUnitId($units, 'Piece'),
                'supplier_id' => $this->getSupplierId($suppliers, 'Parts Supplier'),
                'purchase_price' => 68000.00,
                'selling_price' => 95000.00,
                'minimum_selling_price' => 82000.00,
                'minimum_stock' => 100,
                'maximum_stock' => 1000,
                'reorder_level' => 150,
                'current_stock' => 385,
                'weight' => 0.13,
                'length' => 5.20,
                'width' => 5.20,
                'height' => 1.50,
                'is_taxable' => true,
                'tax_rate' => 11.00,
                'type' => 'spare_parts',
                'is_active' => true,
                'is_serialized' => false,
                'is_batch_tracked' => true,
                'notes' => 'Common replacement part untuk electric motor. Batch tracking untuk quality assurance.',
                'created_by' => $createdBy,
            ],
            [
                'sku' => 'SPR-BR-002',
                'barcode' => '8994234567002',
                'name' => 'Tapered Roller Bearing 30205 (25x52x16.25mm)',
                'description' => 'Tapered roller bearing 30205, untuk aplikasi heavy load, inner diameter 25mm, outer diameter 52mm, width 16.25mm',
                'category_id' => $this->getCategoryId($categories, 'Spare Parts'),
                'brand' => 'NTN',
                'unit_id' => $this->getUnitId($units, 'Piece'),
                'supplier_id' => $this->getSupplierId($suppliers, 'Parts Supplier'),
                'purchase_price' => 95000.00,
                'selling_price' => 135000.00,
                'minimum_selling_price' => 118000.00,
                'minimum_stock' => 50,
                'maximum_stock' => 500,
                'reorder_level' => 80,
                'current_stock' => 165,
                'weight' => 0.19,
                'length' => 5.20,
                'width' => 5.20,
                'height' => 1.63,
                'is_taxable' => true,
                'tax_rate' => 11.00,
                'type' => 'spare_parts',
                'is_active' => true,
                'is_serialized' => false,
                'is_batch_tracked' => true,
                'notes' => 'Heavy duty bearing untuk industrial machinery. Original branded product.',
                'created_by' => $createdBy,
            ],

            // ========================================
            // SPARE PARTS - Belts & Chains
            // ========================================
            [
                'sku' => 'SPR-BT-001',
                'barcode' => '8994234567010',
                'name' => 'V-Belt A53 (13x1350mm)',
                'description' => 'Classical V-belt type A53, top width 13mm, length 1350mm (53 inch), untuk mesin industri dan conveyor',
                'category_id' => $this->getCategoryId($categories, 'Spare Parts'),
                'brand' => 'Gates',
                'unit_id' => $this->getUnitId($units, 'Piece'),
                'supplier_id' => $this->getSupplierId($suppliers, 'Parts Supplier'),
                'purchase_price' => 95000.00,
                'selling_price' => 135000.00,
                'minimum_selling_price' => 118000.00,
                'minimum_stock' => 50,
                'maximum_stock' => 500,
                'reorder_level' => 75,
                'current_stock' => 185,
                'weight' => 0.39,
                'length' => 135.00,
                'width' => 1.30,
                'height' => 0.80,
                'is_taxable' => true,
                'tax_rate' => 11.00,
                'type' => 'spare_parts',
                'is_active' => true,
                'is_serialized' => false,
                'is_batch_tracked' => false,
                'notes' => 'Standard industrial V-belt. Check tension regularly untuk optimal performance.',
                'created_by' => $createdBy,
            ],

            // ========================================
            // OFFICE SUPPLIES - Paper
            // ========================================
            [
                'sku' => 'OFC-PP-001',
                'barcode' => '8995234567001',
                'name' => 'Kertas A4 80gsm Sinar Dunia (1 Ream = 500 sheets)',
                'description' => 'Kertas fotokopi A4 80gsm premium quality, whiteness 102-104%, untuk printer laser dan inkjet, dimensi 210x297mm',
                'category_id' => $this->getCategoryId($categories, 'Stationery'),
                'brand' => 'Sinar Dunia',
                'unit_id' => $this->getUnitId($units, 'Ream'),
                'supplier_id' => $this->getSupplierId($suppliers, 'Office Supplier'),
                'purchase_price' => 38000.00,
                'selling_price' => 52000.00,
                'minimum_selling_price' => 46000.00,
                'minimum_stock' => 200,
                'maximum_stock' => 3000,
                'reorder_level' => 350,
                'current_stock' => 875,
                'weight' => 2.50,
                'length' => 30.00,
                'width' => 21.50,
                'height' => 5.50,
                'is_taxable' => true,
                'tax_rate' => 11.00,
                'type' => 'consumable',
                'is_active' => true,
                'is_serialized' => false,
                'is_batch_tracked' => false,
                'notes' => 'Standard office paper. Store in dry place to prevent moisture.',
                'created_by' => $createdBy,
            ],
            [
                'sku' => 'OFC-PP-002',
                'barcode' => '8995234567002',
                'name' => 'Kertas A4 70gsm PaperOne (1 Ream = 500 sheets)',
                'description' => 'Kertas fotokopi A4 70gsm ekonomis, whiteness 100%, untuk daily printing needs',
                'category_id' => $this->getCategoryId($categories, 'Stationery'),
                'brand' => 'PaperOne',
                'unit_id' => $this->getUnitId($units, 'Ream'),
                'supplier_id' => $this->getSupplierId($suppliers, 'Office Supplier'),
                'purchase_price' => 32000.00,
                'selling_price' => 45000.00,
                'minimum_selling_price' => 40000.00,
                'minimum_stock' => 200,
                'maximum_stock' => 3000,
                'reorder_level' => 350,
                'current_stock' => 1120,
                'weight' => 2.20,
                'length' => 30.00,
                'width' => 21.50,
                'height' => 5.00,
                'is_taxable' => true,
                'tax_rate' => 11.00,
                'type' => 'consumable',
                'is_active' => true,
                'is_serialized' => false,
                'is_batch_tracked' => false,
                'notes' => 'Budget-friendly paper untuk internal documents.',
                'created_by' => $createdBy,
            ],

            // ========================================
            // OFFICE FURNITURE
            // ========================================
            [
                'sku' => 'OFC-FR-001',
                'barcode' => '8995234567010',
                'name' => 'Kursi Kantor Ergonomis Mesh High-Back',
                'description' => 'Kursi kantor ergonomis dengan sandaran punggung mesh breathable, headrest adjustable, lumbar support, armrest 3D adjustable, hydraulic lift, base chrome 5 star, beban max 120kg',
                'category_id' => $this->getCategoryId($categories, 'Furniture'),
                'brand' => 'Ergotec',
                'unit_id' => $this->getUnitId($units, 'Piece'),
                'supplier_id' => $this->getSupplierId($suppliers, 'Office Supplier'),
                'purchase_price' => 1450000.00,
                'selling_price' => 1950000.00,
                'minimum_selling_price' => 1720000.00,
                'minimum_stock' => 15,
                'maximum_stock' => 300,
                'reorder_level' => 25,
                'current_stock' => 68,
                'weight' => 18.50,
                'length' => 70.00,
                'width' => 70.00,
                'height' => 125.00,
                'is_taxable' => true,
                'tax_rate' => 11.00,
                'type' => 'finished_goods',
                'is_active' => true,
                'is_serialized' => true,
                'is_batch_tracked' => false,
                'notes' => 'Premium ergonomic office chair. Garansi 2 tahun untuk hydraulic dan struktur.',
                'created_by' => $createdBy,
            ],
            [
                'sku' => 'OFC-FR-002',
                'barcode' => '8995234567011',
                'name' => 'Meja Kerja Kantor 120x60cm dengan Laci',
                'description' => 'Meja kerja kantor modern minimalis ukuran 120x60cm, ketinggian 75cm, material MDF laminasi, 2 laci samping, cable management hole, warna walnut',
                'category_id' => $this->getCategoryId($categories, 'Furniture'),
                'brand' => 'IKEA',
                'unit_id' => $this->getUnitId($units, 'Piece'),
                'supplier_id' => $this->getSupplierId($suppliers, 'Office Supplier'),
                'purchase_price' => 980000.00,
                'selling_price' => 1350000.00,
                'minimum_selling_price' => 1200000.00,
                'minimum_stock' => 10,
                'maximum_stock' => 150,
                'reorder_level' => 20,
                'current_stock' => 42,
                'weight' => 28.00,
                'length' => 120.00,
                'width' => 60.00,
                'height' => 75.00,
                'is_taxable' => true,
                'tax_rate' => 11.00,
                'type' => 'finished_goods',
                'is_active' => true,
                'is_serialized' => false,
                'is_batch_tracked' => true,
                'notes' => 'Modern office desk dengan laci penyimpanan. Assembly required.',
                'created_by' => $createdBy,
            ],

            // ========================================
            // CHEMICALS - Lubricants
            // ========================================
            [
                'sku' => 'CHM-LB-001',
                'barcode' => '8996234567001',
                'name' => 'Shell Helix Ultra 5W-40 Fully Synthetic (4 Liter)',
                'description' => 'Oli mesin fully synthetic premium untuk gasoline engines, SAE 5W-40, API SN Plus, ACEA A3/B4, protection hingga 15,000km',
                'category_id' => $this->getCategoryId($categories, 'Chemicals'),
                'brand' => 'Shell',
                'unit_id' => $this->getUnitId($units, 'Jerigen'),
                'supplier_id' => $this->getSupplierId($suppliers, 'Chemical Supplier'),
                'purchase_price' => 385000.00,
                'selling_price' => 525000.00,
                'minimum_selling_price' => 475000.00,
                'minimum_stock' => 80,
                'maximum_stock' => 1500,
                'reorder_level' => 150,
                'current_stock' => 420,
                'weight' => 3.60,
                'length' => 22.00,
                'width' => 15.00,
                'height' => 28.00,
                'is_taxable' => true,
                'tax_rate' => 11.00,
                'type' => 'consumable',
                'is_active' => true,
                'is_serialized' => false,
                'is_batch_tracked' => true,
                'notes' => 'Premium engine oil. Store in cool place away from direct sunlight. Batch tracking mandatory.',
                'created_by' => $createdBy,
            ],
            [
                'sku' => 'CHM-LB-002',
                'barcode' => '8996234567002',
                'name' => 'Castrol GTX 15W-50 Mineral Oil (4 Liter)',
                'description' => 'Oli mesin mineral untuk gasoline engines, SAE 15W-50, API SL, suitable untuk iklim tropis, protection 5,000-7,000km',
                'category_id' => $this->getCategoryId($categories, 'Chemicals'),
                'brand' => 'Castrol',
                'unit_id' => $this->getUnitId($units, 'Jerigen'),
                'supplier_id' => $this->getSupplierId($suppliers, 'Chemical Supplier'),
                'purchase_price' => 165000.00,
                'selling_price' => 235000.00,
                'minimum_selling_price' => 210000.00,
                'minimum_stock' => 100,
                'maximum_stock' => 2000,
                'reorder_level' => 200,
                'current_stock' => 680,
                'weight' => 3.50,
                'length' => 22.00,
                'width' => 15.00,
                'height' => 28.00,
                'is_taxable' => true,
                'tax_rate' => 11.00,
                'type' => 'consumable',
                'is_active' => true,
                'is_serialized' => false,
                'is_batch_tracked' => true,
                'notes' => 'Standard mineral oil untuk older engines. Batch tracking untuk quality control.',
                'created_by' => $createdBy,
            ],

            // ========================================
            // CHEMICALS - Cleaning
            // ========================================
            [
                'sku' => 'CHM-CL-001',
                'barcode' => '8996234567010',
                'name' => 'Detergen Bubuk Industrial Super Clean (25kg/sak)',
                'description' => 'Detergen bubuk industrial grade untuk laundry komersial, high foam, whitening booster, enzyme active, untuk washing machine kapasitas besar',
                'category_id' => $this->getCategoryId($categories, 'Chemicals'),
                'brand' => 'Industrial Clean',
                'unit_id' => $this->getUnitId($units, 'Bag'),
                'supplier_id' => $this->getSupplierId($suppliers, 'Chemical Supplier'),
                'purchase_price' => 285000.00,
                'selling_price' => 385000.00,
                'minimum_selling_price' => 345000.00,
                'minimum_stock' => 80,
                'maximum_stock' => 800,
                'reorder_level' => 120,
                'current_stock' => 285,
                'weight' => 25.00,
                'length' => 55.00,
                'width' => 38.00,
                'height' => 18.00,
                'is_taxable' => true,
                'tax_rate' => 11.00,
                'type' => 'consumable',
                'is_active' => true,
                'is_serialized' => false,
                'is_batch_tracked' => true,
                'notes' => 'Industrial laundry detergent. Store in dry place away from food items. Wear gloves when handling.',
                'created_by' => $createdBy,
            ],

            // ========================================
            // SAFETY EQUIPMENT
            // ========================================
            [
                'sku' => 'SAF-EQ-001',
                'barcode' => '8997234567001',
                'name' => 'Sepatu Safety Steel Toe Boots High Cut',
                'description' => 'Sepatu keselamatan kerja high cut boots dengan steel toe cap 200J impact, steel midsole anti-puncture, oil resistant rubber sole, leather upper, size 39-45',
                'category_id' => $this->getCategoryId($categories, 'Consumables'),
                'brand' => 'Safety First Pro',
                'unit_id' => $this->getUnitId($units, 'Pair'),
                'supplier_id' => $this->getSupplierId($suppliers, 'Safety Equipment Supplier'),
                'purchase_price' => 285000.00,
                'selling_price' => 395000.00,
                'minimum_selling_price' => 350000.00,
                'minimum_stock' => 60,
                'maximum_stock' => 600,
                'reorder_level' => 100,
                'current_stock' => 245,
                'weight' => 1.45,
                'length' => 32.00,
                'width' => 18.00,
                'height' => 15.00,
                'is_taxable' => true,
                'tax_rate' => 11.00,
                'type' => 'finished_goods',
                'is_active' => true,
                'is_serialized' => false,
                'is_batch_tracked' => true,
                'notes' => 'Safety boots comply dengan SNI standard. Multiple sizes stock required (39-45).',
                'created_by' => $createdBy,
            ],
            [
                'sku' => 'SAF-EQ-002',
                'barcode' => '8997234567002',
                'name' => 'Helm Safety ABS Hard Hat dengan Ratchet',
                'description' => 'Helm keselamatan kerja material ABS high impact resistant, 6-point ratchet suspension, ventilation slots, chin strap, comply SNI 1811, berbagai warna',
                'category_id' => $this->getCategoryId($categories, 'Consumables'),
                'brand' => 'ProSafe',
                'unit_id' => $this->getUnitId($units, 'Piece'),
                'supplier_id' => $this->getSupplierId($suppliers, 'Safety Equipment Supplier'),
                'purchase_price' => 45000.00,
                'selling_price' => 68000.00,
                'minimum_selling_price' => 60000.00,
                'minimum_stock' => 100,
                'maximum_stock' => 1500,
                'reorder_level' => 200,
                'current_stock' => 485,
                'weight' => 0.42,
                'length' => 28.00,
                'width' => 24.00,
                'height' => 16.00,
                'is_taxable' => true,
                'tax_rate' => 11.00,
                'type' => 'finished_goods',
                'is_active' => true,
                'is_serialized' => false,
                'is_batch_tracked' => true,
                'notes' => 'SNI certified safety helmet. Available colors: white, yellow, red, blue, orange.',
                'created_by' => $createdBy,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }

        $this->command->info('✓ Created ' . count($products) . ' products successfully with detailed specifications!');
    }

    /**
     * Get category ID by name
     */
    private function getCategoryId($categories, $categoryName): ?int
    {
        $category = $categories->firstWhere('name', $categoryName);
        return $category ? $category->id : $categories->first()?->id;
    }

    /**
     * Get unit ID by name
     */
    private function getUnitId($units, $unitName): ?int
    {
        $unit = $units->firstWhere('name', $unitName);
        return $unit ? $unit->id : $units->first()?->id;
    }

    /**
     * Get supplier ID by name
     */
    private function getSupplierId($suppliers, $supplierName): ?int
    {
        if ($suppliers->isEmpty()) {
            return null;
        }
        $supplier = $suppliers->firstWhere('name', $supplierName);
        return $supplier ? $supplier->id : $suppliers->first()?->id;
    }
}