<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\ProductCategory;
use App\Models\User;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $adminUser = User::first();
        $createdBy = $adminUser ? $adminUser->id : null;

        // Ambil categories (pastikan ProductCategorySeeder sudah dijalankan)
        $categories = ProductCategory::all();

        if ($categories->isEmpty()) {
            $this->command->warn('Tidak ada product category. Membuat produk tanpa kategori.');
        }

        $products = [
            // Electronics
            [
                'sku' => 'ELC-001',
                'barcode' => '8991234567001',
                'name' => 'Samsung Galaxy S24',
                'description' => 'Smartphone flagship dengan kamera 200MP dan layar AMOLED 6.8 inch',
                'category_id' => $this->getCategoryId($categories, 'Electronics'),
                'unit_of_measure' => 'pcs',
                'weight_kg' => 0.23,
                'length_cm' => 16.20,
                'width_cm' => 7.60,
                'height_cm' => 0.79,
                'packaging_type' => 'carton',
                'is_batch_tracked' => true,
                'is_serial_tracked' => true,
                'is_expiry_tracked' => false,
                'shelf_life_days' => null,
                'reorder_level' => 50,
                'reorder_quantity' => 100,
                'min_stock_level' => 30,
                'max_stock_level' => 500,
                'is_hazmat' => false,
                'temperature_min' => 15.00,
                'temperature_max' => 25.00,
                'is_active' => true,
                'created_by' => $createdBy,
            ],
            [
                'sku' => 'ELC-002',
                'barcode' => '8991234567002',
                'name' => 'MacBook Pro 16" M3',
                'description' => 'Laptop profesional dengan chip M3 dan RAM 32GB',
                'category_id' => $this->getCategoryId($categories, 'Electronics'),
                'unit_of_measure' => 'pcs',
                'weight_kg' => 2.15,
                'length_cm' => 35.57,
                'width_cm' => 24.81,
                'height_cm' => 1.55,
                'packaging_type' => 'carton',
                'is_batch_tracked' => true,
                'is_serial_tracked' => true,
                'is_expiry_tracked' => false,
                'shelf_life_days' => null,
                'reorder_level' => 20,
                'reorder_quantity' => 50,
                'min_stock_level' => 10,
                'max_stock_level' => 200,
                'is_hazmat' => false,
                'temperature_min' => 10.00,
                'temperature_max' => 30.00,
                'is_active' => true,
                'created_by' => $createdBy,
            ],

            // Food & Beverage
            [
                'sku' => 'FNB-001',
                'barcode' => '8992234567001',
                'name' => 'Indomie Goreng 85g',
                'description' => 'Mi instan goreng original',
                'category_id' => $this->getCategoryId($categories, 'Food'),
                'unit_of_measure' => 'box',
                'weight_kg' => 0.085,
                'length_cm' => 18.00,
                'width_cm' => 8.00,
                'height_cm' => 6.00,
                'packaging_type' => 'carton',
                'is_batch_tracked' => true,
                'is_serial_tracked' => false,
                'is_expiry_tracked' => true,
                'shelf_life_days' => 365,
                'reorder_level' => 500,
                'reorder_quantity' => 2000,
                'min_stock_level' => 300,
                'max_stock_level' => 10000,
                'is_hazmat' => false,
                'temperature_min' => 15.00,
                'temperature_max' => 30.00,
                'is_active' => true,
                'created_by' => $createdBy,
            ],
            [
                'sku' => 'FNB-002',
                'barcode' => '8992234567002',
                'name' => 'Coca Cola 330ml Can',
                'description' => 'Minuman berkarbonasi kemasan kaleng',
                'category_id' => $this->getCategoryId($categories, 'Beverage'),
                'unit_of_measure' => 'pcs',
                'weight_kg' => 0.35,
                'length_cm' => 6.60,
                'width_cm' => 6.60,
                'height_cm' => 12.00,
                'packaging_type' => 'carton',
                'is_batch_tracked' => true,
                'is_serial_tracked' => false,
                'is_expiry_tracked' => true,
                'shelf_life_days' => 270,
                'reorder_level' => 1000,
                'reorder_quantity' => 5000,
                'min_stock_level' => 500,
                'max_stock_level' => 20000,
                'is_hazmat' => false,
                'temperature_min' => 4.00,
                'temperature_max' => 25.00,
                'is_active' => true,
                'created_by' => $createdBy,
            ],

            // Automotive
            [
                'sku' => 'AUT-001',
                'barcode' => '8993234567001',
                'name' => 'Oli Mesin Shell Helix 1L',
                'description' => 'Oli mesin sintetik SAE 10W-40',
                'category_id' => $this->getCategoryId($categories, 'Automotive'),
                'unit_of_measure' => 'liter',
                'weight_kg' => 0.95,
                'length_cm' => 10.00,
                'width_cm' => 10.00,
                'height_cm' => 20.00,
                'packaging_type' => 'drum',
                'is_batch_tracked' => true,
                'is_serial_tracked' => false,
                'is_expiry_tracked' => true,
                'shelf_life_days' => 1825, // 5 tahun
                'reorder_level' => 200,
                'reorder_quantity' => 500,
                'min_stock_level' => 100,
                'max_stock_level' => 2000,
                'is_hazmat' => true,
                'temperature_min' => 5.00,
                'temperature_max' => 35.00,
                'is_active' => true,
                'created_by' => $createdBy,
            ],
            [
                'sku' => 'AUT-002',
                'barcode' => '8993234567002',
                'name' => 'Ban Michelin 185/65R15',
                'description' => 'Ban radial untuk mobil sedan',
                'category_id' => $this->getCategoryId($categories, 'Automotive'),
                'unit_of_measure' => 'pcs',
                'weight_kg' => 8.50,
                'length_cm' => 62.00,
                'width_cm' => 62.00,
                'height_cm' => 18.50,
                'packaging_type' => 'bulk',
                'is_batch_tracked' => true,
                'is_serial_tracked' => false,
                'is_expiry_tracked' => false,
                'shelf_life_days' => null,
                'reorder_level' => 50,
                'reorder_quantity' => 100,
                'min_stock_level' => 30,
                'max_stock_level' => 500,
                'is_hazmat' => false,
                'temperature_min' => 5.00,
                'temperature_max' => 40.00,
                'is_active' => true,
                'created_by' => $createdBy,
            ],

            // Furniture
            [
                'sku' => 'FUR-001',
                'barcode' => '8994234567001',
                'name' => 'Kursi Kantor Ergonomis',
                'description' => 'Kursi kantor dengan sandaran punggung mesh',
                'category_id' => $this->getCategoryId($categories, 'Furniture'),
                'unit_of_measure' => 'pcs',
                'weight_kg' => 15.00,
                'length_cm' => 70.00,
                'width_cm' => 70.00,
                'height_cm' => 120.00,
                'packaging_type' => 'carton',
                'is_batch_tracked' => false,
                'is_serial_tracked' => false,
                'is_expiry_tracked' => false,
                'shelf_life_days' => null,
                'reorder_level' => 20,
                'reorder_quantity' => 50,
                'min_stock_level' => 10,
                'max_stock_level' => 200,
                'is_hazmat' => false,
                'temperature_min' => null,
                'temperature_max' => null,
                'is_active' => true,
                'created_by' => $createdBy,
            ],
            [
                'sku' => 'FUR-002',
                'barcode' => '8994234567002',
                'name' => 'Meja Komputer Minimalis',
                'description' => 'Meja komputer kayu dengan laci',
                'category_id' => $this->getCategoryId($categories, 'Furniture'),
                'unit_of_measure' => 'pcs',
                'weight_kg' => 25.00,
                'length_cm' => 120.00,
                'width_cm' => 60.00,
                'height_cm' => 75.00,
                'packaging_type' => 'carton',
                'is_batch_tracked' => false,
                'is_serial_tracked' => false,
                'is_expiry_tracked' => false,
                'shelf_life_days' => null,
                'reorder_level' => 15,
                'reorder_quantity' => 30,
                'min_stock_level' => 10,
                'max_stock_level' => 150,
                'is_hazmat' => false,
                'temperature_min' => null,
                'temperature_max' => null,
                'is_active' => true,
                'created_by' => $createdBy,
            ],

            // Chemicals
            [
                'sku' => 'CHM-001',
                'barcode' => '8995234567001',
                'name' => 'Detergen Bubuk 1kg',
                'description' => 'Detergen bubuk untuk mesin cuci',
                'category_id' => $this->getCategoryId($categories, 'Chemical'),
                'unit_of_measure' => 'kg',
                'weight_kg' => 1.00,
                'length_cm' => 25.00,
                'width_cm' => 18.00,
                'height_cm' => 8.00,
                'packaging_type' => 'bag',
                'is_batch_tracked' => true,
                'is_serial_tracked' => false,
                'is_expiry_tracked' => true,
                'shelf_life_days' => 730, // 2 tahun
                'reorder_level' => 300,
                'reorder_quantity' => 1000,
                'min_stock_level' => 200,
                'max_stock_level' => 5000,
                'is_hazmat' => false,
                'temperature_min' => 10.00,
                'temperature_max' => 30.00,
                'is_active' => true,
                'created_by' => $createdBy,
            ],
            [
                'sku' => 'CHM-002',
                'barcode' => '8995234567002',
                'name' => 'Cairan Pembersih Lantai 5L',
                'description' => 'Pembersih lantai antiseptik',
                'category_id' => $this->getCategoryId($categories, 'Chemical'),
                'unit_of_measure' => 'liter',
                'weight_kg' => 5.20,
                'length_cm' => 25.00,
                'width_cm' => 18.00,
                'height_cm' => 30.00,
                'packaging_type' => 'drum',
                'is_batch_tracked' => true,
                'is_serial_tracked' => false,
                'is_expiry_tracked' => true,
                'shelf_life_days' => 1095, // 3 tahun
                'reorder_level' => 100,
                'reorder_quantity' => 500,
                'min_stock_level' => 50,
                'max_stock_level' => 2000,
                'is_hazmat' => true,
                'temperature_min' => 5.00,
                'temperature_max' => 35.00,
                'is_active' => true,
                'created_by' => $createdBy,
            ],

            // Textile
            [
                'sku' => 'TEX-001',
                'barcode' => '8996234567001',
                'name' => 'Kaos Polos Cotton Combed',
                'description' => 'Kaos polos 100% cotton combed 30s',
                'category_id' => $this->getCategoryId($categories, 'Textile'),
                'unit_of_measure' => 'pcs',
                'weight_kg' => 0.20,
                'length_cm' => 30.00,
                'width_cm' => 25.00,
                'height_cm' => 2.00,
                'packaging_type' => 'carton',
                'is_batch_tracked' => true,
                'is_serial_tracked' => false,
                'is_expiry_tracked' => false,
                'shelf_life_days' => null,
                'reorder_level' => 200,
                'reorder_quantity' => 500,
                'min_stock_level' => 100,
                'max_stock_level' => 2000,
                'is_hazmat' => false,
                'temperature_min' => 15.00,
                'temperature_max' => 30.00,
                'is_active' => true,
                'created_by' => $createdBy,
            ],

            // Pharmaceutical
            [
                'sku' => 'PHA-001',
                'barcode' => '8997234567001',
                'name' => 'Paracetamol 500mg Strip',
                'description' => 'Obat pereda demam dan nyeri',
                'category_id' => $this->getCategoryId($categories, 'Pharmaceutical'),
                'unit_of_measure' => 'box',
                'weight_kg' => 0.05,
                'length_cm' => 10.00,
                'width_cm' => 5.00,
                'height_cm' => 2.00,
                'packaging_type' => 'carton',
                'is_batch_tracked' => true,
                'is_serial_tracked' => false,
                'is_expiry_tracked' => true,
                'shelf_life_days' => 1095, // 3 tahun
                'reorder_level' => 500,
                'reorder_quantity' => 2000,
                'min_stock_level' => 300,
                'max_stock_level' => 10000,
                'is_hazmat' => false,
                'temperature_min' => 15.00,
                'temperature_max' => 25.00,
                'is_active' => true,
                'created_by' => $createdBy,
            ],

            // Building Materials
            [
                'sku' => 'BLD-001',
                'barcode' => '8998234567001',
                'name' => 'Semen Portland 50kg',
                'description' => 'Semen Portland type I',
                'category_id' => $this->getCategoryId($categories, 'Building'),
                'unit_of_measure' => 'kg',
                'weight_kg' => 50.00,
                'length_cm' => 80.00,
                'width_cm' => 40.00,
                'height_cm' => 10.00,
                'packaging_type' => 'bag',
                'is_batch_tracked' => true,
                'is_serial_tracked' => false,
                'is_expiry_tracked' => false,
                'shelf_life_days' => null,
                'reorder_level' => 100,
                'reorder_quantity' => 500,
                'min_stock_level' => 50,
                'max_stock_level' => 2000,
                'is_hazmat' => false,
                'temperature_min' => 10.00,
                'temperature_max' => 40.00,
                'is_active' => true,
                'created_by' => $createdBy,
            ],

            // Frozen Food
            [
                'sku' => 'FRZ-001',
                'barcode' => '8999234567001',
                'name' => 'Ayam Nugget 500g',
                'description' => 'Nugget ayam beku siap goreng',
                'category_id' => $this->getCategoryId($categories, 'Food'),
                'unit_of_measure' => 'pcs',
                'weight_kg' => 0.50,
                'length_cm' => 20.00,
                'width_cm' => 15.00,
                'height_cm' => 5.00,
                'packaging_type' => 'carton',
                'is_batch_tracked' => true,
                'is_serial_tracked' => false,
                'is_expiry_tracked' => true,
                'shelf_life_days' => 365,
                'reorder_level' => 200,
                'reorder_quantity' => 500,
                'min_stock_level' => 100,
                'max_stock_level' => 2000,
                'is_hazmat' => false,
                'temperature_min' => -18.00,
                'temperature_max' => -10.00,
                'is_active' => true,
                'created_by' => $createdBy,
            ],

            // Stationery
            [
                'sku' => 'STA-001',
                'barcode' => '8990234567001',
                'name' => 'Kertas A4 80gsm Box',
                'description' => 'Kertas fotokopi A4 80gsm isi 5 rim',
                'category_id' => $this->getCategoryId($categories, 'Stationery'),
                'unit_of_measure' => 'box',
                'weight_kg' => 12.50,
                'length_cm' => 30.00,
                'width_cm' => 21.00,
                'height_cm' => 28.00,
                'packaging_type' => 'carton',
                'is_batch_tracked' => false,
                'is_serial_tracked' => false,
                'is_expiry_tracked' => false,
                'shelf_life_days' => null,
                'reorder_level' => 50,
                'reorder_quantity' => 100,
                'min_stock_level' => 30,
                'max_stock_level' => 500,
                'is_hazmat' => false,
                'temperature_min' => 15.00,
                'temperature_max' => 30.00,
                'is_active' => true,
                'created_by' => $createdBy,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }

        $this->command->info('Created ' . count($products) . ' products successfully!');
    }

    /**
     * Get category ID by name
     */
    private function getCategoryId($categories, $categoryName): ?int
    {
        $category = $categories->firstWhere('name', $categoryName);
        return $category ? $category->id : null;
    }
}