<?php
// database/seeders/RoleSeeder.php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class RoleSeeder extends Seeder
{
    public function run(): void
    {
        $roles = [
            [
                'name' => 'Super Admin',
                'slug' => 'super-admin',
                'description' => 'Full system access with all permissions',
                'permissions' => json_encode([
                    'users' => ['view', 'create', 'edit', 'delete'],
                    'roles' => ['view', 'create', 'edit', 'delete'],
                    'warehouses' => ['view', 'create', 'edit', 'delete'],
                    'storage_areas' => ['view', 'create', 'edit', 'delete'],
                    'storage_bins' => ['view', 'create', 'edit', 'delete'],
                    'products' => ['view', 'create', 'edit', 'delete'],
                    'customers' => ['view', 'create', 'edit', 'delete'],
                    'vendors' => ['view', 'create', 'edit', 'delete'],
                    'purchase_orders' => ['view', 'create', 'edit', 'delete', 'approve'],
                    'sales_orders' => ['view', 'create', 'edit', 'delete', 'approve'],
                    'inventory' => ['view', 'create', 'edit', 'delete', 'adjust'],
                    'good_receiving' => ['view', 'create', 'edit', 'delete', 'approve'],
                    'putaway' => ['view', 'create', 'edit', 'delete', 'assign'],
                    'picking' => ['view', 'create', 'edit', 'delete', 'assign'],
                    'packing' => ['view', 'create', 'edit', 'delete'],
                    'delivery' => ['view', 'create', 'edit', 'delete'],
                    'returns' => ['view', 'create', 'edit', 'delete', 'approve'],
                    'transfers' => ['view', 'create', 'edit', 'delete', 'approve'],
                    'replenishment' => ['view', 'create', 'edit', 'delete'],
                    'stock_opname' => ['view', 'create', 'edit', 'delete', 'approve'],
                    'stock_adjustment' => ['view', 'create', 'edit', 'delete', 'approve'],
                    'reports' => ['view', 'export'],
                    'settings' => ['view', 'edit'],
                ]),
            ],
            [
                'name' => 'Warehouse Manager',
                'slug' => 'warehouse-manager',
                'description' => 'Manage warehouse operations and staff',
                'permissions' => json_encode([
                    'users' => ['view'],
                    'warehouses' => ['view', 'edit'],
                    'storage_areas' => ['view', 'create', 'edit'],
                    'storage_bins' => ['view', 'create', 'edit'],
                    'products' => ['view', 'create', 'edit'],
                    'customers' => ['view'],
                    'vendors' => ['view'],
                    'purchase_orders' => ['view', 'create', 'edit', 'approve'],
                    'sales_orders' => ['view', 'create', 'edit', 'approve'],
                    'inventory' => ['view', 'create', 'edit', 'adjust'],
                    'good_receiving' => ['view', 'create', 'edit', 'approve'],
                    'putaway' => ['view', 'create', 'edit', 'assign'],
                    'picking' => ['view', 'create', 'edit', 'assign'],
                    'packing' => ['view', 'create', 'edit'],
                    'delivery' => ['view', 'create', 'edit'],
                    'returns' => ['view', 'create', 'edit', 'approve'],
                    'transfers' => ['view', 'create', 'edit', 'approve'],
                    'replenishment' => ['view', 'create', 'edit'],
                    'stock_opname' => ['view', 'create', 'edit', 'approve'],
                    'stock_adjustment' => ['view', 'create', 'edit', 'approve'],
                    'reports' => ['view', 'export'],
                ]),
            ],
            [
                'name' => 'Warehouse Supervisor',
                'slug' => 'warehouse-supervisor',
                'description' => 'Supervise daily warehouse operations',
                'permissions' => json_encode([
                    'warehouses' => ['view'],
                    'storage_areas' => ['view'],
                    'storage_bins' => ['view', 'edit'],
                    'products' => ['view'],
                    'customers' => ['view'],
                    'vendors' => ['view'],
                    'purchase_orders' => ['view', 'create', 'edit'],
                    'sales_orders' => ['view', 'create', 'edit'],
                    'inventory' => ['view', 'edit'],
                    'good_receiving' => ['view', 'create', 'edit'],
                    'putaway' => ['view', 'create', 'edit', 'assign'],
                    'picking' => ['view', 'create', 'edit', 'assign'],
                    'packing' => ['view', 'create', 'edit'],
                    'delivery' => ['view', 'create', 'edit'],
                    'returns' => ['view', 'create', 'edit'],
                    'transfers' => ['view', 'create', 'edit'],
                    'replenishment' => ['view', 'create', 'edit'],
                    'stock_opname' => ['view', 'create', 'edit'],
                    'stock_adjustment' => ['view', 'create', 'edit'],
                    'reports' => ['view'],
                ]),
            ],
            [
                'name' => 'Receiving Staff',
                'slug' => 'receiving-staff',
                'description' => 'Handle inbound operations and receiving',
                'permissions' => json_encode([
                    'warehouses' => ['view'],
                    'storage_bins' => ['view'],
                    'products' => ['view'],
                    'vendors' => ['view'],
                    'purchase_orders' => ['view'],
                    'inventory' => ['view'],
                    'good_receiving' => ['view', 'create', 'edit'],
                    'putaway' => ['view'],
                    'returns' => ['view', 'create'],
                    'reports' => ['view'],
                ]),
            ],
            [
                'name' => 'Warehouse Operator',
                'slug' => 'warehouse-operator',
                'description' => 'Execute putaway and replenishment tasks',
                'permissions' => json_encode([
                    'warehouses' => ['view'],
                    'storage_bins' => ['view'],
                    'products' => ['view'],
                    'inventory' => ['view'],
                    'putaway' => ['view', 'edit'],
                    'replenishment' => ['view', 'edit'],
                    'transfers' => ['view', 'edit'],
                ]),
            ],
            [
                'name' => 'Picker',
                'slug' => 'picker',
                'description' => 'Execute picking orders',
                'permissions' => json_encode([
                    'warehouses' => ['view'],
                    'storage_bins' => ['view'],
                    'products' => ['view'],
                    'inventory' => ['view'],
                    'sales_orders' => ['view'],
                    'picking' => ['view', 'edit'],
                ]),
            ],
            [
                'name' => 'Packer',
                'slug' => 'packer',
                'description' => 'Execute packing orders',
                'permissions' => json_encode([
                    'warehouses' => ['view'],
                    'products' => ['view'],
                    'sales_orders' => ['view'],
                    'picking' => ['view'],
                    'packing' => ['view', 'create', 'edit'],
                ]),
            ],
            [
                'name' => 'Dispatcher',
                'slug' => 'dispatcher',
                'description' => 'Manage outbound deliveries',
                'permissions' => json_encode([
                    'warehouses' => ['view'],
                    'customers' => ['view'],
                    'sales_orders' => ['view'],
                    'packing' => ['view'],
                    'delivery' => ['view', 'create', 'edit'],
                    'returns' => ['view', 'create'],
                    'reports' => ['view'],
                ]),
            ],
            [
                'name' => 'Inventory Controller',
                'slug' => 'inventory-controller',
                'description' => 'Manage inventory accuracy and stock control',
                'permissions' => json_encode([
                    'warehouses' => ['view'],
                    'storage_bins' => ['view'],
                    'products' => ['view'],
                    'inventory' => ['view', 'edit', 'adjust'],
                    'stock_opname' => ['view', 'create', 'edit'],
                    'stock_adjustment' => ['view', 'create', 'edit'],
                    'reports' => ['view', 'export'],
                ]),
            ],
            [
                'name' => 'Quality Control',
                'slug' => 'quality-control',
                'description' => 'Inspect and approve quality of goods',
                'permissions' => json_encode([
                    'warehouses' => ['view'],
                    'products' => ['view'],
                    'vendors' => ['view'],
                    'good_receiving' => ['view', 'edit'],
                    'returns' => ['view', 'edit'],
                    'reports' => ['view'],
                ]),
            ],
            [
                'name' => 'Customer Service',
                'slug' => 'customer-service',
                'description' => 'Handle customer orders and inquiries',
                'permissions' => json_encode([
                    'warehouses' => ['view'],
                    'products' => ['view'],
                    'customers' => ['view', 'create', 'edit'],
                    'sales_orders' => ['view', 'create', 'edit'],
                    'inventory' => ['view'],
                    'delivery' => ['view'],
                    'returns' => ['view', 'create'],
                    'reports' => ['view'],
                ]),
            ],
            [
                'name' => 'Purchasing Staff',
                'slug' => 'purchasing-staff',
                'description' => 'Manage purchase orders and vendor relations',
                'permissions' => json_encode([
                    'warehouses' => ['view'],
                    'products' => ['view', 'create', 'edit'],
                    'vendors' => ['view', 'create', 'edit'],
                    'purchase_orders' => ['view', 'create', 'edit'],
                    'inventory' => ['view'],
                    'reports' => ['view'],
                ]),
            ],
            [
                'name' => 'Finance Staff',
                'slug' => 'finance-staff',
                'description' => 'View financial and transaction reports',
                'permissions' => json_encode([
                    'purchase_orders' => ['view'],
                    'sales_orders' => ['view'],
                    'delivery' => ['view'],
                    'returns' => ['view'],
                    'reports' => ['view', 'export'],
                ]),
            ],
            [
                'name' => 'Reporting Analyst',
                'slug' => 'reporting-analyst',
                'description' => 'Access to all reports and analytics',
                'permissions' => json_encode([
                    'warehouses' => ['view'],
                    'products' => ['view'],
                    'customers' => ['view'],
                    'vendors' => ['view'],
                    'inventory' => ['view'],
                    'purchase_orders' => ['view'],
                    'sales_orders' => ['view'],
                    'reports' => ['view', 'export'],
                ]),
            ],
            [
                'name' => 'Driver',
                'slug' => 'driver',
                'description' => 'Mobile access for delivery operations',
                'permissions' => json_encode([
                    'delivery' => ['view', 'edit'],
                    'returns' => ['view', 'create'],
                ]),
            ],
        ];

        foreach ($roles as $role) {
            DB::table('roles')->insert([
                'name' => $role['name'],
                'slug' => $role['slug'],
                'description' => $role['description'],
                'permissions' => $role['permissions'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}