<?php

namespace Database\Seeders;

use App\Models\Vendor;
use App\Models\User;
use Illuminate\Database\Seeder;

class VendorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $adminUser = User::first();
        $createdBy = $adminUser ? $adminUser->id : null;

        $vendors = [
            // Electronics Vendors
            [
                'code' => 'VEND001',
                'name' => 'PT Samsung Electronics Indonesia',
                'company_name' => 'PT Samsung Electronics Indonesia',
                'email' => 'b2b@samsung.co.id',
                'phone' => '021-5890-0000',
                'address' => 'Jl. Jababeka Raya Blok F 29-33',
                'city' => 'Cikarang',
                'province' => 'Jawa Barat',
                'postal_code' => '17530',
                'country' => 'Indonesia',
                'tax_id' => '01.001.234.5-678.000',
                'payment_terms_days' => 45,
                'contact_person' => 'Kim Min-soo',
                'contact_phone' => '0812-1111-2222',
                'is_active' => true,
                'notes' => 'Vendor utama untuk produk elektronik Samsung',
                'created_by' => $createdBy,
            ],
            [
                'code' => 'VEND002',
                'name' => 'PT Apple Indonesia',
                'company_name' => 'PT Apple Indonesia',
                'email' => 'enterprise@apple.co.id',
                'phone' => '021-2992-1888',
                'address' => 'Pacific Place Mall, SCBD Lot 3-5',
                'city' => 'Jakarta Selatan',
                'province' => 'DKI Jakarta',
                'postal_code' => '12190',
                'country' => 'Indonesia',
                'tax_id' => '01.002.345.6-789.000',
                'payment_terms_days' => 60,
                'contact_person' => 'John Anderson',
                'contact_phone' => '0813-2222-3333',
                'is_active' => true,
                'notes' => 'Authorized distributor Apple products',
                'created_by' => $createdBy,
            ],
            [
                'code' => 'VEND003',
                'name' => 'PT Asus Technology Indonesia',
                'company_name' => 'PT Asus Technology Indonesia',
                'email' => 'corporate@asus.co.id',
                'phone' => '021-5021-6868',
                'address' => 'Gedung Cyber 2 Tower, Jl. HR Rasuna Said',
                'city' => 'Jakarta Selatan',
                'province' => 'DKI Jakarta',
                'postal_code' => '12950',
                'country' => 'Indonesia',
                'tax_id' => '01.003.456.7-890.000',
                'payment_terms_days' => 45,
                'contact_person' => 'Chen Wei',
                'contact_phone' => '0821-3333-4444',
                'is_active' => true,
                'notes' => 'Vendor laptop dan komputer',
                'created_by' => $createdBy,
            ],

            // Food & Beverage Vendors
            [
                'code' => 'VEND004',
                'name' => 'PT Indofood CBP Sukses Makmur',
                'company_name' => 'PT Indofood CBP Sukses Makmur',
                'email' => 'sales@indofoodcbp.co.id',
                'phone' => '021-2650-8888',
                'address' => 'Sudirman Plaza, Indofood Tower',
                'city' => 'Jakarta Selatan',
                'province' => 'DKI Jakarta',
                'postal_code' => '12920',
                'country' => 'Indonesia',
                'tax_id' => '01.004.567.8-901.000',
                'payment_terms_days' => 30,
                'contact_person' => 'Siti Rahma',
                'contact_phone' => '0822-4444-5555',
                'is_active' => true,
                'notes' => 'Supplier produk makanan instant',
                'created_by' => $createdBy,
            ],
            [
                'code' => 'VEND005',
                'name' => 'PT Coca-Cola Amatil Indonesia',
                'company_name' => 'PT Coca-Cola Amatil Indonesia',
                'email' => 'orders@coca-cola.co.id',
                'phone' => '021-7592-7000',
                'address' => 'Jl. Raya Bekasi KM 22',
                'city' => 'Jakarta Timur',
                'province' => 'DKI Jakarta',
                'postal_code' => '13920',
                'country' => 'Indonesia',
                'tax_id' => '01.005.678.9-012.000',
                'payment_terms_days' => 30,
                'contact_person' => 'Michael Johnson',
                'contact_phone' => '0813-5555-6666',
                'is_active' => true,
                'notes' => 'Distributor minuman ringan',
                'created_by' => $createdBy,
            ],
            [
                'code' => 'VEND006',
                'name' => 'PT Nestle Indonesia',
                'company_name' => 'PT Nestle Indonesia',
                'email' => 'business@nestle.co.id',
                'phone' => '021-7884-5678',
                'address' => 'Perkantoran Hijau Arkadia, Tower C',
                'city' => 'Jakarta Pusat',
                'province' => 'DKI Jakarta',
                'postal_code' => '10250',
                'country' => 'Indonesia',
                'tax_id' => '01.006.789.0-123.000',
                'payment_terms_days' => 30,
                'contact_person' => 'Pierre Dubois',
                'contact_phone' => '0821-6666-7777',
                'is_active' => true,
                'notes' => 'Vendor produk makanan dan minuman',
                'created_by' => $createdBy,
            ],

            // Automotive Vendors
            [
                'code' => 'VEND007',
                'name' => 'PT Shell Indonesia',
                'company_name' => 'PT Shell Indonesia',
                'email' => 'lubricants@shell.com',
                'phone' => '021-2553-3000',
                'address' => 'Energy Building, SCBD Lot 11A',
                'city' => 'Jakarta Selatan',
                'province' => 'DKI Jakarta',
                'postal_code' => '12190',
                'country' => 'Indonesia',
                'tax_id' => '01.007.890.1-234.000',
                'payment_terms_days' => 45,
                'contact_person' => 'James Williams',
                'contact_phone' => '0822-7777-8888',
                'is_active' => true,
                'notes' => 'Supplier oli dan pelumas',
                'created_by' => $createdBy,
            ],
            [
                'code' => 'VEND008',
                'name' => 'PT Michelin Indonesia',
                'company_name' => 'PT Michelin Indonesia',
                'email' => 'sales@michelin.co.id',
                'phone' => '021-8067-7000',
                'address' => 'Jl. MT Haryono Kav. 8',
                'city' => 'Jakarta Selatan',
                'province' => 'DKI Jakarta',
                'postal_code' => '12810',
                'country' => 'Indonesia',
                'tax_id' => '01.008.901.2-345.000',
                'payment_terms_days' => 60,
                'contact_person' => 'Antoine Bernard',
                'contact_phone' => '0813-8888-9999',
                'is_active' => true,
                'notes' => 'Vendor ban berkualitas premium',
                'created_by' => $createdBy,
            ],

            // Furniture Vendors
            [
                'code' => 'VEND009',
                'name' => 'PT IKEA Indonesia',
                'company_name' => 'PT IKEA Indonesia',
                'email' => 'b2b@ikea.co.id',
                'phone' => '021-5021-5021',
                'address' => 'Alam Sutera, Jl. Jalur Sutera Barat',
                'city' => 'Tangerang',
                'province' => 'Banten',
                'postal_code' => '15143',
                'country' => 'Indonesia',
                'tax_id' => '01.009.012.3-456.000',
                'payment_terms_days' => 30,
                'contact_person' => 'Lars Andersson',
                'contact_phone' => '0821-9999-0000',
                'is_active' => true,
                'notes' => 'Supplier furnitur modern',
                'created_by' => $createdBy,
            ],
            [
                'code' => 'VEND010',
                'name' => 'CV Jati Luhur Furniture',
                'company_name' => 'CV Jati Luhur Furniture',
                'email' => 'order@jatiluhur.com',
                'phone' => '0291-123456',
                'address' => 'Jl. Raya Jepara-Kudus KM 12',
                'city' => 'Jepara',
                'province' => 'Jawa Tengah',
                'postal_code' => '59419',
                'country' => 'Indonesia',
                'tax_id' => '01.010.123.4-567.000',
                'payment_terms_days' => 30,
                'contact_person' => 'Bambang Sutopo',
                'contact_phone' => '0856-0000-1111',
                'is_active' => true,
                'notes' => 'Produsen furnitur kayu jati',
                'created_by' => $createdBy,
            ],

            // Chemical Vendors
            [
                'code' => 'VEND011',
                'name' => 'PT Unilever Indonesia',
                'company_name' => 'PT Unilever Indonesia',
                'email' => 'customer.service@unilever.co.id',
                'phone' => '021-7885-6000',
                'address' => 'Grha Unilever, Green Office Park',
                'city' => 'Tangerang',
                'province' => 'Banten',
                'postal_code' => '15314',
                'country' => 'Indonesia',
                'tax_id' => '01.011.234.5-678.000',
                'payment_terms_days' => 30,
                'contact_person' => 'Sarah Mitchell',
                'contact_phone' => '0822-1111-2222',
                'is_active' => true,
                'notes' => 'Vendor produk pembersih dan detergen',
                'created_by' => $createdBy,
            ],
            [
                'code' => 'VEND012',
                'name' => 'PT Kao Indonesia',
                'company_name' => 'PT Kao Indonesia',
                'email' => 'info@kao.co.id',
                'phone' => '021-2963-8888',
                'address' => 'Jl. M.H. Thamrin Kav. 51',
                'city' => 'Jakarta Pusat',
                'province' => 'DKI Jakarta',
                'postal_code' => '10350',
                'country' => 'Indonesia',
                'tax_id' => '01.012.345.6-789.000',
                'payment_terms_days' => 30,
                'contact_person' => 'Tanaka Hiroshi',
                'contact_phone' => '0813-2222-3333',
                'is_active' => true,
                'notes' => 'Supplier produk pembersih premium',
                'created_by' => $createdBy,
            ],

            // Textile Vendors
            [
                'code' => 'VEND013',
                'name' => 'PT Pan Brothers Tex',
                'company_name' => 'PT Pan Brothers Tex',
                'email' => 'sales@panbrothers.com',
                'phone' => '022-8783-1234',
                'address' => 'Jl. Raya Tangerang KM 23',
                'city' => 'Tangerang',
                'province' => 'Banten',
                'postal_code' => '15810',
                'country' => 'Indonesia',
                'tax_id' => '01.013.456.7-890.000',
                'payment_terms_days' => 45,
                'contact_person' => 'Gunawan Pramudya',
                'contact_phone' => '0821-3333-4444',
                'is_active' => true,
                'notes' => 'Produsen tekstil dan garmen',
                'created_by' => $createdBy,
            ],

            // Pharmaceutical Vendors
            [
                'code' => 'VEND014',
                'name' => 'PT Kalbe Farma',
                'company_name' => 'PT Kalbe Farma',
                'email' => 'corporate@kalbe.co.id',
                'phone' => '021-4280-6808',
                'address' => 'Gedung Kalbe, Jl. Let. Jend. Suprapto',
                'city' => 'Jakarta Pusat',
                'province' => 'DKI Jakarta',
                'postal_code' => '10510',
                'country' => 'Indonesia',
                'tax_id' => '01.014.567.8-901.000',
                'payment_terms_days' => 30,
                'contact_person' => 'Dr. Andi Wijaya',
                'contact_phone' => '0822-4444-5555',
                'is_active' => true,
                'notes' => 'Vendor obat-obatan dan suplemen',
                'created_by' => $createdBy,
            ],
            [
                'code' => 'VEND015',
                'name' => 'PT Dexa Medica',
                'company_name' => 'PT Dexa Medica',
                'email' => 'order@dexamedica.com',
                'phone' => '021-4212-0000',
                'address' => 'Jl. Bambang Ery Soepomo No. 7',
                'city' => 'Palembang',
                'province' => 'Sumatera Selatan',
                'postal_code' => '30137',
                'country' => 'Indonesia',
                'tax_id' => '01.015.678.9-012.000',
                'payment_terms_days' => 45,
                'contact_person' => 'Dr. Siti Nurhaliza',
                'contact_phone' => '0813-5555-6666',
                'is_active' => true,
                'notes' => 'Distributor farmasi nasional',
                'created_by' => $createdBy,
            ],

            // Building Materials Vendors
            [
                'code' => 'VEND016',
                'name' => 'PT Semen Indonesia (Persero)',
                'company_name' => 'PT Semen Indonesia (Persero)',
                'email' => 'commercial@semenindonesia.co.id',
                'phone' => '031-398-1732',
                'address' => 'Gedung Utama Kompleks Perkantoran PT Semen Indonesia',
                'city' => 'Gresik',
                'province' => 'Jawa Timur',
                'postal_code' => '61122',
                'country' => 'Indonesia',
                'tax_id' => '01.016.789.0-123.000',
                'payment_terms_days' => 30,
                'contact_person' => 'Ahmad Fauzi',
                'contact_phone' => '0821-6666-7777',
                'is_active' => true,
                'notes' => 'Vendor semen dan bahan bangunan',
                'created_by' => $createdBy,
            ],
            [
                'code' => 'VEND017',
                'name' => 'PT Mowilex Indonesia',
                'company_name' => 'PT Mowilex Indonesia',
                'email' => 'info@mowilex.com',
                'phone' => '021-4614-7777',
                'address' => 'Jl. Raya Bogor KM 27',
                'city' => 'Jakarta Timur',
                'province' => 'DKI Jakarta',
                'postal_code' => '13850',
                'country' => 'Indonesia',
                'tax_id' => '01.017.890.1-234.000',
                'payment_terms_days' => 30,
                'contact_person' => 'Hendra Gunawan',
                'contact_phone' => '0822-7777-8888',
                'is_active' => true,
                'notes' => 'Supplier cat dan pelapis',
                'created_by' => $createdBy,
            ],

            // Stationery Vendors
            [
                'code' => 'VEND018',
                'name' => 'PT Sinar Dunia Makmur (Sidu)',
                'company_name' => 'PT Sinar Dunia Makmur',
                'email' => 'sales@sidu.co.id',
                'phone' => '031-731-1234',
                'address' => 'Jl. Raya Rungkut Industri',
                'city' => 'Surabaya',
                'province' => 'Jawa Timur',
                'postal_code' => '60293',
                'country' => 'Indonesia',
                'tax_id' => '01.018.901.2-345.000',
                'payment_terms_days' => 30,
                'contact_person' => 'Rudi Hartono',
                'contact_phone' => '0813-8888-9999',
                'is_active' => true,
                'notes' => 'Produsen kertas dan alat tulis',
                'created_by' => $createdBy,
            ],

            // Inactive Vendor (contoh)
            [
                'code' => 'VEND019',
                'name' => 'PT Global Trading Sejahtera',
                'company_name' => 'PT Global Trading Sejahtera',
                'email' => 'contact@globaltrading.co.id',
                'phone' => '021-9876-5432',
                'address' => 'Jl. Mangga Dua Raya',
                'city' => 'Jakarta Utara',
                'province' => 'DKI Jakarta',
                'postal_code' => '14430',
                'country' => 'Indonesia',
                'tax_id' => '01.019.012.3-456.000',
                'payment_terms_days' => 30,
                'contact_person' => 'Robert Chen',
                'contact_phone' => '0821-9999-0000',
                'is_active' => false,
                'notes' => 'Vendor tidak aktif - kualitas produk tidak sesuai standar',
                'created_by' => $createdBy,
            ],

            // International Vendor
            [
                'code' => 'VEND020',
                'name' => 'Dell Technologies Singapore',
                'company_name' => 'Dell Technologies Singapore Pte Ltd',
                'email' => 'sea_sales@dell.com',
                'phone' => '+65-6701-8000',
                'address' => '1 Fusionopolis Place, #14-01 Galaxis',
                'city' => 'Singapore',
                'province' => 'Singapore',
                'postal_code' => '138522',
                'country' => 'Singapore',
                'tax_id' => '199002748H',
                'payment_terms_days' => 60,
                'contact_person' => 'David Tan',
                'contact_phone' => '+65-9123-4567',
                'is_active' => true,
                'notes' => 'Vendor internasional untuk laptop dan server',
                'created_by' => $createdBy,
            ],
        ];

        foreach ($vendors as $vendor) {
            Vendor::create($vendor);
        }

        $this->command->info('Created ' . count($vendors) . ' vendors successfully!');
    }
}