<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('settings', function (Blueprint $table) {
            $table->id();
            $table->string('key')->unique()->comment('Setting key identifier');
            $table->text('value')->nullable()->comment('Setting value (can store JSON, string, number, etc)');
            $table->enum('type', ['string', 'integer', 'boolean', 'json', 'text', 'file', 'image', 'color', 'email', 'url'])->default('string')->comment('Data type of the value');
            $table->string('group', 50)->default('general')->comment('Setting group/category');
            $table->text('description')->nullable()->comment('Description of the setting');
            $table->boolean('is_public')->default(false)->comment('Can be accessed publicly');
            $table->boolean('is_editable')->default(true)->comment('Can be edited from UI');
            $table->integer('order')->default(0)->comment('Display order');
            $table->foreignId('updated_by')->nullable()->constrained('users')->nullOnDelete();
            $table->timestamps();

            // Indexes for better performance
            $table->index('group');
            $table->index('is_public');
            $table->index('order');
        });

        // Insert default settings
        $this->insertDefaultSettings();
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('settings');
    }

    /**
     * Insert default system settings
     */
    private function insertDefaultSettings(): void
    {
        $now = now();
        
        DB::table('settings')->insert([
            // Website Identity Settings
            [
                'key' => 'site_name',
                'value' => 'WMS Pro',
                'type' => 'string',
                'group' => 'identity',
                'description' => 'Website name displayed in browser title and header',
                'is_public' => true,
                'is_editable' => true,
                'order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'site_title',
                'value' => 'WMS Pro - Professional Warehouse Management System',
                'type' => 'string',
                'group' => 'identity',
                'description' => 'Website title for SEO',
                'is_public' => true,
                'is_editable' => true,
                'order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'site_tagline',
                'value' => 'Manage Your Warehouse with Ease',
                'type' => 'string',
                'group' => 'identity',
                'description' => 'Short tagline or slogan',
                'is_public' => true,
                'is_editable' => true,
                'order' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'site_description',
                'value' => 'Professional warehouse management system for modern businesses',
                'type' => 'text',
                'group' => 'identity',
                'description' => 'Website description for SEO meta',
                'is_public' => true,
                'is_editable' => true,
                'order' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'site_keywords',
                'value' => 'warehouse, management, inventory, stock, wms',
                'type' => 'text',
                'group' => 'identity',
                'description' => 'SEO keywords (comma separated)',
                'is_public' => true,
                'is_editable' => true,
                'order' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'site_logo',
                'value' => null,
                'type' => 'image',
                'group' => 'identity',
                'description' => 'Main logo (PNG, recommended: 200x50px)',
                'is_public' => true,
                'is_editable' => true,
                'order' => 6,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'site_logo_dark',
                'value' => null,
                'type' => 'image',
                'group' => 'identity',
                'description' => 'Logo for dark mode',
                'is_public' => true,
                'is_editable' => true,
                'order' => 7,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'site_logo_small',
                'value' => null,
                'type' => 'image',
                'group' => 'identity',
                'description' => 'Small logo for mobile/collapsed sidebar',
                'is_public' => true,
                'is_editable' => true,
                'order' => 8,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'site_favicon',
                'value' => null,
                'type' => 'image',
                'group' => 'identity',
                'description' => 'Favicon (ICO/PNG, 32x32px)',
                'is_public' => true,
                'is_editable' => true,
                'order' => 9,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'site_og_image',
                'value' => null,
                'type' => 'image',
                'group' => 'identity',
                'description' => 'Open Graph image for social sharing (1200x630px)',
                'is_public' => true,
                'is_editable' => true,
                'order' => 10,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Company Information
            [
                'key' => 'company_name',
                'value' => 'Your Company Name',
                'type' => 'string',
                'group' => 'company',
                'description' => 'Legal company name',
                'is_public' => true,
                'is_editable' => true,
                'order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'company_email',
                'value' => null,
                'type' => 'email',
                'group' => 'company',
                'description' => 'Primary company email',
                'is_public' => true,
                'is_editable' => true,
                'order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'company_phone',
                'value' => null,
                'type' => 'string',
                'group' => 'company',
                'description' => 'Primary phone number',
                'is_public' => true,
                'is_editable' => true,
                'order' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'company_whatsapp',
                'value' => null,
                'type' => 'string',
                'group' => 'company',
                'description' => 'WhatsApp number (with country code)',
                'is_public' => true,
                'is_editable' => true,
                'order' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'company_address',
                'value' => null,
                'type' => 'text',
                'group' => 'company',
                'description' => 'Complete company address',
                'is_public' => true,
                'is_editable' => true,
                'order' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'company_city',
                'value' => null,
                'type' => 'string',
                'group' => 'company',
                'description' => 'City',
                'is_public' => true,
                'is_editable' => true,
                'order' => 6,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'company_state',
                'value' => null,
                'type' => 'string',
                'group' => 'company',
                'description' => 'State/Province',
                'is_public' => true,
                'is_editable' => true,
                'order' => 7,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'company_country',
                'value' => 'Indonesia',
                'type' => 'string',
                'group' => 'company',
                'description' => 'Country',
                'is_public' => true,
                'is_editable' => true,
                'order' => 8,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'company_postal_code',
                'value' => null,
                'type' => 'string',
                'group' => 'company',
                'description' => 'Postal/ZIP code',
                'is_public' => true,
                'is_editable' => true,
                'order' => 9,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'company_website',
                'value' => null,
                'type' => 'url',
                'group' => 'company',
                'description' => 'Company website URL',
                'is_public' => true,
                'is_editable' => true,
                'order' => 10,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'company_tax_number',
                'value' => null,
                'type' => 'string',
                'group' => 'company',
                'description' => 'Tax ID / NPWP',
                'is_public' => false,
                'is_editable' => true,
                'order' => 11,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Theme & Appearance
            [
                'key' => 'theme_primary_color',
                'value' => '#3b82f6',
                'type' => 'color',
                'group' => 'appearance',
                'description' => 'Primary brand color',
                'is_public' => true,
                'is_editable' => true,
                'order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'theme_secondary_color',
                'value' => '#6366f1',
                'type' => 'color',
                'group' => 'appearance',
                'description' => 'Secondary brand color',
                'is_public' => true,
                'is_editable' => true,
                'order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'theme_sidebar_color',
                'value' => '#1f2937',
                'type' => 'color',
                'group' => 'appearance',
                'description' => 'Sidebar background color',
                'is_public' => true,
                'is_editable' => true,
                'order' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'theme_mode',
                'value' => 'light',
                'type' => 'string',
                'group' => 'appearance',
                'description' => 'Default theme mode (light/dark/auto)',
                'is_public' => true,
                'is_editable' => true,
                'order' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Social Media
            [
                'key' => 'social_facebook',
                'value' => null,
                'type' => 'url',
                'group' => 'social',
                'description' => 'Facebook page URL',
                'is_public' => true,
                'is_editable' => true,
                'order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'social_twitter',
                'value' => null,
                'type' => 'url',
                'group' => 'social',
                'description' => 'Twitter/X profile URL',
                'is_public' => true,
                'is_editable' => true,
                'order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'social_instagram',
                'value' => null,
                'type' => 'url',
                'group' => 'social',
                'description' => 'Instagram profile URL',
                'is_public' => true,
                'is_editable' => true,
                'order' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'social_linkedin',
                'value' => null,
                'type' => 'url',
                'group' => 'social',
                'description' => 'LinkedIn profile URL',
                'is_public' => true,
                'is_editable' => true,
                'order' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'social_youtube',
                'value' => null,
                'type' => 'url',
                'group' => 'social',
                'description' => 'YouTube channel URL',
                'is_public' => true,
                'is_editable' => true,
                'order' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Warehouse Settings
            [
                'key' => 'default_warehouse_id',
                'value' => '1',
                'type' => 'integer',
                'group' => 'warehouse',
                'description' => 'Default warehouse ID',
                'is_public' => false,
                'is_editable' => true,
                'order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'enable_multi_warehouse',
                'value' => 'true',
                'type' => 'boolean',
                'group' => 'warehouse',
                'description' => 'Enable multi-warehouse functionality',
                'is_public' => false,
                'is_editable' => true,
                'order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'enable_barcode_scanning',
                'value' => 'true',
                'type' => 'boolean',
                'group' => 'warehouse',
                'description' => 'Enable barcode scanning feature',
                'is_public' => false,
                'is_editable' => true,
                'order' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'default_stock_method',
                'value' => 'FIFO',
                'type' => 'string',
                'group' => 'warehouse',
                'description' => 'Default stock method (FIFO, LIFO, FEFO)',
                'is_public' => false,
                'is_editable' => true,
                'order' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Inventory Settings
            [
                'key' => 'low_stock_threshold',
                'value' => '10',
                'type' => 'integer',
                'group' => 'inventory',
                'description' => 'Low stock alert threshold',
                'is_public' => false,
                'is_editable' => true,
                'order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'enable_negative_stock',
                'value' => 'false',
                'type' => 'boolean',
                'group' => 'inventory',
                'description' => 'Allow negative stock levels',
                'is_public' => false,
                'is_editable' => true,
                'order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'enable_batch_tracking',
                'value' => 'true',
                'type' => 'boolean',
                'group' => 'inventory',
                'description' => 'Enable batch/lot tracking',
                'is_public' => false,
                'is_editable' => true,
                'order' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'enable_serial_tracking',
                'value' => 'true',
                'type' => 'boolean',
                'group' => 'inventory',
                'description' => 'Enable serial number tracking',
                'is_public' => false,
                'is_editable' => true,
                'order' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'enable_expiry_tracking',
                'value' => 'true',
                'type' => 'boolean',
                'group' => 'inventory',
                'description' => 'Enable expiry date tracking',
                'is_public' => false,
                'is_editable' => true,
                'order' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Notification Settings
            [
                'key' => 'enable_email_notifications',
                'value' => 'true',
                'type' => 'boolean',
                'group' => 'notifications',
                'description' => 'Enable email notifications',
                'is_public' => false,
                'is_editable' => true,
                'order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'enable_low_stock_alerts',
                'value' => 'true',
                'type' => 'boolean',
                'group' => 'notifications',
                'description' => 'Enable low stock alert notifications',
                'is_public' => false,
                'is_editable' => true,
                'order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'enable_expiry_alerts',
                'value' => 'true',
                'type' => 'boolean',
                'group' => 'notifications',
                'description' => 'Enable expiry date alert notifications',
                'is_public' => false,
                'is_editable' => true,
                'order' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'expiry_alert_days',
                'value' => '30',
                'type' => 'integer',
                'group' => 'notifications',
                'description' => 'Days before expiry to send alerts',
                'is_public' => false,
                'is_editable' => true,
                'order' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Report Settings
            [
                'key' => 'default_date_format',
                'value' => 'd/m/Y',
                'type' => 'string',
                'group' => 'report',
                'description' => 'Default date format (d/m/Y, Y-m-d, m/d/Y)',
                'is_public' => false,
                'is_editable' => true,
                'order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'default_time_format',
                'value' => 'H:i',
                'type' => 'string',
                'group' => 'report',
                'description' => 'Default time format (H:i, h:i A)',
                'is_public' => false,
                'is_editable' => true,
                'order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'default_currency',
                'value' => 'IDR',
                'type' => 'string',
                'group' => 'report',
                'description' => 'Default currency code (IDR, USD, EUR)',
                'is_public' => false,
                'is_editable' => true,
                'order' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'currency_symbol',
                'value' => 'Rp',
                'type' => 'string',
                'group' => 'report',
                'description' => 'Currency symbol',
                'is_public' => false,
                'is_editable' => true,
                'order' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'items_per_page',
                'value' => '15',
                'type' => 'integer',
                'group' => 'report',
                'description' => 'Default items per page in tables',
                'is_public' => false,
                'is_editable' => true,
                'order' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Security Settings
            [
                'key' => 'enable_2fa',
                'value' => 'false',
                'type' => 'boolean',
                'group' => 'security',
                'description' => 'Enable two-factor authentication',
                'is_public' => false,
                'is_editable' => true,
                'order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'session_lifetime',
                'value' => '120',
                'type' => 'integer',
                'group' => 'security',
                'description' => 'Session lifetime in minutes',
                'is_public' => false,
                'is_editable' => true,
                'order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'password_min_length',
                'value' => '8',
                'type' => 'integer',
                'group' => 'security',
                'description' => 'Minimum password length',
                'is_public' => false,
                'is_editable' => true,
                'order' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // System Settings
            [
                'key' => 'maintenance_mode',
                'value' => 'false',
                'type' => 'boolean',
                'group' => 'system',
                'description' => 'Enable maintenance mode',
                'is_public' => false,
                'is_editable' => true,
                'order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'timezone',
                'value' => 'Asia/Jakarta',
                'type' => 'string',
                'group' => 'system',
                'description' => 'System timezone',
                'is_public' => false,
                'is_editable' => true,
                'order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'language',
                'value' => 'id',
                'type' => 'string',
                'group' => 'system',
                'description' => 'Default system language (id, en)',
                'is_public' => false,
                'is_editable' => true,
                'order' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);
    }
};